model:
    type: base
    encoder: resnet50
    mlp_layers: 3

dataset:
    dir: /home/intern1/Linemod_preprocessed/renders/ufcoco/
    train_ratio: 0.9

train_params:
    epochs: 25
    bs: 8
    lr: 0.001
    resume_from_checkpoint: False
    start_epoch: 0
